### ISSUE TITLE
removing single precision option?

### ISSUE THREAD

**Issue by brucefan1983** [brucefan1983/GPUMD#24]
Single precision is usually about 2x faster than double precision, but it is not always safe to use single precision. I feel that there is no need to keep the option to use single precision. By using double precision only, the readability of the code can be improved. I want to minimize (if it is impossible to eliminate) the use of #ifdef.

How do you think? @AlexGabourie

**Comment by AlexGabourie** [comment]
It's probably safer to remove the single precision option. 

In my own experience, I've found that the single precision calculations give comparable results to double precision when I'm computing thermal conductivity. However, I'm sure there are many circumstances where the results are different in a non-negligible way. Also, I do not see a 2x improvement in speed with the switch from double to single precision (~20%-25%) improvement in speed, likely due to some other bottlenecks in my runs. 

The cluster I use for simulations has a 2 day run limit. I sometimes find that constraint to be limiting and some GPUMD runs will not finish. In those cases, I might switch to single precision because there is no option to scale to multiple GPUs or continue simulations from checkpoints. That's really the only use case I have.

**Comment by brucefan1983** [comment]
Yes, for small systems, there is even no 2x speedup by switching to single
precision. In the literature, mixed precision (single precision for force
evaluation and double precision for force accumulation and other
calculations) has been proposed. While this is much safer than naive single
precision, I feel that it will complicate the code a lot, which is not I
want. So, I will remove the single precision option.

AlexG <notifications@github.com> 于 2019年2月11日周一 03:00写道：

**Comment by brucefan1983** [comment]
I have just removed the single precision option.

**Comment by brucefan1983** [comment]
BTW, a 2-day running time is very restrictive. In our cluster, common jobs are allowed to run 3 days, and long jobs can run 2 weeks. That is why I have not bothered to implement a multi-GPU version yet. But have you noticed that there is a `dump_restart` command now? This will not ensure perfect restart in some cases (thermostat variables are not saved), but should be adequate for most applications.
