### ISSUE TITLE
Add support for binary dump file

### ISSUE THREAD

**Issue by andeplane** [brucefan1983/GPUMD#4]
When simulating either large systems or long time scales, parsing a text file (`xyz.out`) may be very slow. I suggest at least supporting just a binary file that is easily loaded in numpy (Python) or similar.

**Comment by brucefan1983** [comment]
OK. Good suggestion! I will try to do it. I have to figure out how to do it first :-)

**Comment by andeplane** [comment]
What would be ideal is to actually use netcdf format (this is a binary format supported by many programs), but that would require that you link the code with their library. My guess is that you want to have a self contained code that just works out of the box. 

If you could show me how to add a command like
`dump_style text`, I could implement the binary output for you.

**Comment by brucefan1983** [comment]
Yes, I don't want to make GPUMD depend on other packages, unless it is really unavoidable. For example, I have tried to use CUB (https://nvlabs.github.io/cub/) before, but switched to Thrust later. 

Making the output readable by other softwares like ovito is a very good idea. I did not do this because I did not need it in my previous research. I only used MATLAB to analysed my results :-)

It's very nice if you can contribute this part. There are many per-atom data which can be dumped, like velocities, forces, virials, and potentials. Perhaps the dump_style can apply to all these data?

To implement this, you need to 
1) add a variable such as "dump_style" to the Parameters structure in common.h so that you can use it later. 
2) add an else if to the parse() function in parse.cu and add a corresponding process_dump_style() function.
3) Modify (or rewrite) the code in the dump.cu file.

**Comment by brucefan1983** [comment]
This has been solved by Alex.
