### ISSUE TITLE
Training NEP for mixed dataset

### ISSUE THREAD

**Issue by artempi** [brucefan1983/GPUMD#540]
I am training NEP with a dataset that has both bulk structures, as well as some oxide structures. It seems that the training goes fine in the beginning, however, both F-train and F-test begin to increase close to the end of the training process.
I have uploaded my files into https://github.com/CUANTAM/NEP-Training
![LossOUT](https://github.com/brucefan1983/GPUMD/assets/14337432/2deddce4-9105-4459-bcff-f3093b4d466d)

My guess is that I may need a larger basis size, maybe 15 15 instead of 12 12. 
version     4
type        5 Hf O Si W  Zr
cutoff      5 5        # 
n_max       12 6        # 
basis_size  12 12      # 
l_max       4       # 
neuron      40         # 
lambda_1    0.05        # 
lambda_2    0.05        # 
population  50         # 
batch       1000       # 
generation  200000     #

**Comment by brucefan1983** [comment]
The major problem is that you have too weak regularization.

I suggest you start from the default settings, just writing a single line:

type 5 Hf O Si W Zr

in nep.in

Zheyong

**Comment by artempi** [comment]
@brucefan1983 
I was able to get smaller F-test errors with the default settings:
![image](https://github.com/brucefan1983/GPUMD/assets/14337432/d80948ae-c72b-418c-8bb9-f0734e52d2af)

Is there a way to improve further with custom settings?
Thank you

**Comment by brucefan1983** [comment]
if you do not study radiation damage, there is no need to add ZBL. 
When you need to add ZBL, it is usually required to have some dimer structures to make the connection between NEP and ZBL fixed.

**Comment by brucefan1983** [comment]
The major parameters to tune are the cutoff radii, which are 8 A and 4 A in the default setting. You can try a few combinations:
1) your original ones 5 A, 5A
2) the default ones: 8 A, 4 A
3) perhap you can try another set: 7 A, 5 A

Then you can decide which to take based on accuarcy and speed

**Comment by brucefan1983** [comment]
Actually, the defult regularization might be too strong. I have revised the default regularization a few days ago (https://github.com/brucefan1983/GPUMD/pull/541), and you can try to see if that gives better training and testing accuracy.

**Comment by brucefan1983** [comment]
I think there is no real issue here, so I will close it.

**Comment by tomasfbouvier** [comment]
I'm facing a kinda similar issue. When training with a single atomic species I obtain a good regularization curve like the one shown in the examples:

![Figure_4](https://github.com/user-attachments/assets/4c9d08cf-4640-4b44-9b04-e6660efce6bf)

However on the same dataset and the same parameters varying only the number of atomic species, I get a curve that is stacked on the maximum of the regularization and does not seem to drop after many generations. 

![Figure_3](https://github.com/user-attachments/assets/a30a7f81-4f3f-4c0a-99a9-6fb398efb222)

I thought since there are the double of parameters to train, the lambda1 should be increased according to the fomula sqrt(N)/1000 that you use as a default. But I see in the source code that this is divided by the number of species...

In addition: We are working with Si containing impurities. We already have a nep model that works fine for the Si. Would it make sense to freeze a pretrained Si model and train on top of that the impurity mode, i.e the Si-X and X-X interaction (X is the impurity).

**Comment by brucefan1983** [comment]
The reason for dividing by the number of species is that we are now using a multi-loss training algorithm [https://doi.org/10.1038/s41467-024-54554-x] which essentially (but not completely) train the parameters for different species independently.

BTW, I found the energy loss curve in the second plot better than that in the first plot. The results in the first plot does not look good to me.
